package com.sdg.bec.fragment

import android.os.Bundle
import android.view.View
import com.sdg.bec.constant.Constant
import com.sdg.bec.databinding.FragmentMineBinding
import com.sdg.bec.db.Phrase
import com.sdg.bec.db.Sentence
import com.sdg.bec.db.Words
import com.sdg.bec.presenter.PMine
import com.sdg.bec.utils.MyUtil
import com.sdg.bec.view.VMine
import com.sdg.common.base.BaseBindingFragment

class MineFragment : BaseBindingFragment<FragmentMineBinding, VMine, PMine>(),VMine{

    companion object {
        fun newInstance(): MineFragment? {
            val fragment: MineFragment = MineFragment()
            val args = Bundle()
            fragment.arguments = args
            return fragment
        }
    }

    override fun initData() {

    }

    override fun createPresenter(): PMine = PMine()

    private fun addWords(){
        var important = Constant.Important.primary
        var classify = Constant.SentenceClassify.life
        var status = Constant.Status.add
        var time = MyUtil.getTime()

        Words(MyUtil.getUUID(),important,"adj","在国外的，海外","abroad",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","缺席，缺乏，不在场","absence",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","缺席的","absent",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","承担，支付，吞并，吸收","absorb",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","摘要；清单","abstract",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","承兑人","acceptor",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","接近；进入市场；获取","access",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","设施；住宿；贷款","accommodation",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","账户","account",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","增值；利息；自然增长","accrual",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","积累；累积","accumulate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","实现；完成","achieve",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","会计师","accountant",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","承认；感谢；确认","acknowledge",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","获得；购入；取得所有权","acquire",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","收购","acquisition",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj&adv","全体；全面","cross the board",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","代理的","acting",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","活跃的；流通的","active",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","业务；活动","activity",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","真实的；实际的","actual",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","现货","actuals",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","修改；改装；适应","adapt",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","延期；休会","adjourn",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","调整；修改","adjust",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","行政管理","administration",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","采纳；批准","adopt",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","采纳；采用","adoption",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","预付款；提高","advance",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","公布，通告；做广告","advertise",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","广告，通告","advertisement",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n&adj","广告业；广告的，与广告有关的","advertising",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","买得起；承受得住；承担责任","afford",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","议事日程","agenda",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","代理人；代理机构；经纪人","agent",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","协定，协议；契约","agreement",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","分配；配给","allocate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","补贴；折扣，折价","allowance",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","合并","amalgamate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","合并，重组","amalgamation",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","强烈的欲望；进取心；雄心","ambition",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","分期偿还","amortize",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","分析；研究","analyze",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","分析；分析后得到的报告","analysis",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","分析员","analyst",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","每年的；按年度计算的","annual",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","预定；抢险；提前使用；期待","anticipate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","吸引力","appeal",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","申请；应用","apply",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","申请人；求职者","applicant",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","申请书；","application",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","被任命人；被委派人；","appointee",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","估价；评估","appraisal",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","赏识，重视；体谅；增值","appreciate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","拨出款项","appropriate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","正式批准；官方认证","approval",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","赞成，满意；批准，通过","approve",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","天资；才能","aptitude",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","套汇；套利交易","arbitrage",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","仲裁；公断；鉴定","arbitration",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","欠款；逾期债款","arrears",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","集合；聚集；装配","assemble",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","评估；估价","assess",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","财产；资产","asset",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","援助；协助；出席","assist",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","审计，审核；查账","audit",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","使...自动化；使...自动操作","automate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","平均为；平均水准","average",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","意识；认识程度","awareness",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","财务支持；赞助","backing",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","回扣；贿赂","backhander",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","积压","backlog",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","无效的；无用的；作废的；亏损的","bad",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","使均衡；余额，收支差额","balance",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n&adj","使破产；破产人，破产公司；破产的，无力偿还债务的；","bankrupt",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","破产；无偿还能力","bankruptcy",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","条状图；柱状图","bar chart",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","谈判，讨价还价；便宜货，交易","bargain",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","设立/形成...的基础；基地，根据地","base",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","品质恶劣的","base-minded",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","一批，一群，一组","batch",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","分批的；不连续的","batch-wise",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","超过，胜过，榨取","beat",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","表现；运转","behave",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","行为，举止；运转情况","behavior",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","基准；衡量标准","benchmark",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","利益；补助，津贴，福利","benefit",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","投标，出价；支付","bit",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","纽约证券交易所","Big Board",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","开账单，开发票；票据，账单","bill",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","广告牌，招粘板","billboard",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","短期脱产进修","block release",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","蓝筹股","blue chip",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","蓝领的","blue-collar",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","蓝图；详细规划","blueprint",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","董事会；膳食","board",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","公债，债券；法律保证书","bond",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","奖金，工作津贴","bonus",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","账簿；账目","books",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","簿记员","bookkeeper",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","推动，促进；宣扬","boost",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","阻碍；瓶颈，窄路","bottleneck",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n&adj","到达底部，建立基础；底部；最后的，根本的","bottom",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","退回，反弹，解雇；反弹，解雇","bounce",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","集思广益；头脑风暴","brainstorm",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","分支；分部","branch",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","商标；品牌","brand",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","收支平衡；不亏不盈","break even",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","突破","breakthrough",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","行贿，买通；贿赂","bribe",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n&adj","摘要；简洁的，扼要的","brief",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","小册子","brochure",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","经纪人，代理人","broker",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","拨款，(为...)节省金钱；预算，预算拨款","budget",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","大量(货物)","bulk",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","牛市","bull market",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n&adj","破产；萧条期；破产的","bust",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","买方市场","buyout",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","呼叫；召集，要求参加；付款要求","call",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","(政治性)活动","campaign",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","取消；废除","cancel",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","求职者，候选人，申请人","candidate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","职工食堂","canteen",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","向...拉票/拉生意/拉订单；细查","canvass",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","加上标题，加上说明；简要说明","caption",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","资本，资金","capital",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","获得，赢得","capture",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","现金","cash",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","目录，产品目录","catalogue",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","大灾难，大祸","catastrophe",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","餐饮服务","catering",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","饮食供应商","caterer",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","证书","certificate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","以书面形式证明","certify",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","连锁店，一系列","chain",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","挑战者","challenger",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","(商品流通的)渠道","channel",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","收费，索价，记账，控告；价钱，费用","charge",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","图表","chart",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","凭照，特许状；章程，宪章","charter",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","核对，核查；支票，餐馆的账单","check",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n&adj","首领；主要的，总的，主席的","chief",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","通告，通函，传单","circular",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","传阅，分送；使流通，使周转","circulate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","流通","circulation",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","伦敦城","the City",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","索赔；要求(权利)","claim",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n&adj","办事员；职员的，办公室的","clerical",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","委托人，顾客","client",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","冷淡的，生意清淡的","cold",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n&adj","广告；商贸的，盈利的","commercial",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","佣金，回扣；代办，委托","commission",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","商品，货物","commodity",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","连通，沟通；书信，口信；通讯","communication",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","公司","company",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","补偿，报酬","compensate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","补偿，赔偿；酬金","compensation",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","比赛，竞争","compete",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","比赛，竞争，竞争对手","competition",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","竞争者，对手","competitor",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","竞争性的","competitive",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","机器元件，组件，部件；部分","component",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","条件，状况；付款条件","condition",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","设备的结构","configuration",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","冲突，争论","conflict",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","联合企业；跨行业公司","conglomerate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","巩固，加强；账目合并，统一","consolidate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","财团","consortium",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","恒定的，不变的","constant",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","咨询人员；顾问","consultant",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","消费者","consumer",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","消耗的；一次性的","consumable",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","意外事件","contingency",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","连续时间","continuum",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","订约，承包；合同，契约","contract",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","承包商，承建人","contractor",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","提供；捐献","contribute",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","贡献；捐献","contribution",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","会谈；谈话","conversation",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","运送；传递；转让","conveyor",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","基本上班时间","core time",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","计算成本；成本，费用","cost",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","成本计算；成本法","costing",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","赊购，赊购制度；信任，信用","credit",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","债权人，贷方","creditor",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","危机，转折点，贷方","crisis",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","关键的","critical",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","货币，通货；流通期","currency",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n&adj","通用的，现行的，当前的；趋势，潮流","current",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","定做，定制","customize",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","习惯，惯例；海关，关税","custom",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","残酷的；激烈的","cut-throat",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","消减；裁剪","cut back",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","降价(出售)的","cut-price",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","简历；履历","CV=curriculum vitae",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","损害，损失；费用；代价，赔款","damage",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","最后时间，期限时间","deadline",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","处理，买卖；大量，买卖，交易","deal",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","经销商，商人","dealer",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","债务","debt",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","债务人；借方","debtor",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","断言，申称；申报进口应纳税的货物","declare",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","下降，衰落，拒绝；下倾，斜面，衰败","decline",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","减少；减少之量","decrease",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","扣除，扣减","deduct",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","变节，背叛；过失，缺点","defect",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n&adj","有缺陷的...；有缺陷的","defective",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","延期，听从；使推迟","defer",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","赤字，不足额","deficit",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","递送，交货","delivery",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","要求，查询；需求，要求","demand",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","存放，堆积；存款，堆积物，押金","deposit",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","仓库，保管处；航空站","depot",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","折旧，使贬值，贬低","depreciate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","压力，降低；使贬值，使降价，使萧条","depress",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","代理人，委托人","deputy",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","货币贬值","devalue",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","通常所吃的食物","diet",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","区别","differentiation",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n&adj","工资差额；有差别的，有级别的","differential",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","尺寸，方面","dimension",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&adj&adv","管理，知道，注意力指向...；直接的；直接地","direct",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","主任，董事，理事","director",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n&adj","指导的，管理的；董事会，指南，号码簿","directory",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","打折；折扣，贴现","discount",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","免职，不予考虑","dismissal",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","分派，派遣；急件，迅速派遣，急于","dispatch",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n&adj","展览；展览；特排的，醒目显示的","display",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","处理，安排，部署","dispose",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","分配，配给物","distribution",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","使不同，使多样化，使变化","diversify",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","处理掉，剥夺","divest",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","股息，红利，津贴，奖金","dividend",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","部门","division",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","滞销品；事业","dog",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj&adv","现付的；付现金","down",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","激动的，戏剧性的","dramatic",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","积极性，能动性，努力","drive",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n&adj","应得物，权力；应付的，应得的","due",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","有活力的，动态的","dynamic",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","工资，收入；收益","eamings",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","效率，功效","efficiency",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","认可；在(票据)背面签名","endorse",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","雇佣，预定；使从事于；承诺，保证(长与that/to连用)","engage",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","给...权力、资格；授权","entitle",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","公平，资产净值，股东权益","equity",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","估计，估价","estimate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","估价，评价","evaluate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","最后的","eventual",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","夸大，夸张","exaggerate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","超越，胜过","exceed",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","展示；展品","exhibit",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","花费，花销","expenditure",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","费用，开支；损失","expense",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","专长，专业知识和技能","expertise",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","公众对某一产品的知悉；广告所达到的观众总数","exposure",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","用于生产的设备；器材","facilities",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","代理人，因素，系数；做代理商，代理经营，把...作为因素计入","factor",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","不合格；失误，延迟","fail",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","可行性，可能性","feasibility",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","反馈","feedback",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n&adj","巧妙对付(或回答)；领域，具体业务；商务的，在某一领域操作或活动的","field",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","把文件归档，提交，申请；文件，档案，卷宗","file",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","填充，供应，供给","fill",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","供给...经费，筹措资金；财政，金融，政学","finance",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","财政的，金融的","financial",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","金融业务，筹资，资金","financing",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","结束的，完成的","finished",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n&adj&adv","使坚定，使牢固，变稳固；公司，商号；坚固的，严格的；稳固地，坚定地","firm",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","解雇，激发，激起","fire",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","财政的，会计的","fiscal",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","确定，使固定在","fix",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","旗舰，同类中最成功的商品，佼佼者","flagship",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","灵活的，可通融的","flexible",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","弹性上班","flextime",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","快车，快船；飞机上的乘客，促销传单","filer",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","发行股票，浮动，实行计划","float",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","失败","flop",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","流动；流程","flow",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","波动，涨落，起伏","fluctuate",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","跟随，遵循，了解；追随","follow",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","预测，预报","forecast",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","框架，结构","framework",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","特许经销；特许经销权","franchise",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","欺诈行为，骗子，假货","fraud",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","免费赠品","freebie",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&adj","做自由作家；自由职业者的","freelance",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","资助，投资；资金，基金，钱","fund",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n&adj","未来，将来，前景；未来的，将来的","future",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","期货，期货合同","futures",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","缺口，差距，隔阂","gap",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","资金搭配率，借入资金和自有资金的比率","gearing radio",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","骗人的玩意儿；花招，好主意，好点子","gimmick",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","目标，目的","goal",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","趋于，达到，求助于，出产；去，进行","go",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n&adj","离去，工作情况；进行中，流行的，现存的","going",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","货物","goods",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","善意，声誉","goodwill",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","设法解决","grapple",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","申诉，抱怨","grievance",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n&adj","总共赚得；总额；毛重的，总的","gross",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","逐渐的，渐进的","gradual",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","聚合，成群；团体","group",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","增长，扩大；栽培","grow",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","增长，发展","growth",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","保证，担保；抵押品，保单","guarantee",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","指导，管理，操纵；领路人，指南","guide",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","支持，交给；掌管，协助，雇员","hand",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v","买卖，经营，操作","handle",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj&adv","困难的；努力地","hard",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","冒...的危险，使遭受危险；危险，危害行为","hazard",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n&adj","主管，负责(v&n)；头的，主要的","head",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","保护，防范，避开，回避；防护或防御的方法；","hedge",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"adj","隐藏的，不明显的","hidden",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"n","层次，层级","hierarchy",classify,time,status).save()
        Words(MyUtil.getUUID(),important,"v&n","出租，受雇，雇用；租金，工钱，租用雇用","hire",classify,time,status).save()

    }

    fun buchong(){
        var important = Constant.Important.primary
        var classify = Constant.SentenceClassify.life
        var status = Constant.Status.add
        var time = MyUtil.getTime()

        Phrase(MyUtil.getUUID(),important,"管理，分配；散布","hand out",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"呈送","hand in",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"递交辞呈","hand in one's notice",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"向...鼓掌","give a (good) hand to",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"有效地处理问题","handle problem efficiently",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"全力以赴","hard all",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"奇缺...","hard up for",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"缺钱","hard up",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"偶然，碰运气","by hazard",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"做无效的猜测","hazard a guess",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"身负重债","over head and ears in debt",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"隐患","a hidden danger",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"言外之意","a hidden meaning",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"等级观念","a sense of hierarchy",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"出租","on/for hire",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"雇工","work for hire",classify,time,status)

    }

    private fun addPhrase(){
        var important = Constant.Important.primary
        var classify = Constant.SentenceClassify.life
        var status = Constant.Status.add
        var time = MyUtil.getTime()

        Phrase(MyUtil.getUUID(),important,"cname","ename",classify,time,status)

        Phrase(MyUtil.getUUID(),important,"海外市场","market abroad",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"缺乏领导","an absence of leadership",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"缺乏...时；当...不在时","in the absence of",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"请假；准假","leave of absence",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"缺席，不在","be absent from",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"被...吞并；为...所吸收","be absorbed by",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"全神贯注于...；热衷于...","be absorbed in",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"把...要点摘录下来","make an abstract of",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"接见，准许出入","give access to",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"进入市场","access to market",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"预订旅馆住宿","book accommodation at a hotel",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"请求付账；请求回答","ask an account",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"与...结清账目；向某人报复","balance accounts",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"为...代理","for account of",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"解释；说明","account for",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"收到一封信","acknowledge a letter",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"甘拜下风","acknowledge the com",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"答谢所受到的关照","acknowledge a favor",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"流通货币","active money",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"实际损失","actual loss",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"使适应于；为...改编","adapt for",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"根据...改编","adapt from",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"使某事物适应...","adapt to",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"评定损失","adjust the losses",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"校正误差","adjust the errors",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"在某人的管理下","under somebody's administration",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"在某人的任期内","during the administration of somebody",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"透支","advance by overdraft",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"银行贷款","bank advance",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"登...广告","advertise for",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"买得起...","afford to buy sth",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"承担得起做...的后果","afford to do sth",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"把...提上日程","place/put sth on the agenda",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"达成一致","come to an agreement",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"达成一致","reach/make an agreement",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"符合...；和...一致","in agreement with",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"无限制；尽兴的","at no allowance",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"考虑到；体谅","make allowance for",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"给补贴费；给零用钱","make an allowance to",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"公司合并","amalgamation of companies",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"野心勃勃","born with an ambition",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"把...分解成","analyze into",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"年度报告","annual report",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"殷切的期望","ardently anticipate",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"引起某人兴趣","make an appeal to somebody",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"适用于；与...接触","be applied to",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"申请","apply for",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"把...运用于...","apply sth to",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"向...询问","apply to",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"求职书","a job application",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"对...做出客观评价","make/give an objective appraisal of",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"多谢厚意","appreciate your kindness",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"拨出款项供...使用","appropriate for",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"包退换的","on approval",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"商品套汇","commodity arbitrage",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"索价，要价","asking price",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"帮助某人做某事","assist somebody to do sth",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"帮助某人做某事","assist somebody in doing sth",classify,time,status).save()

        Phrase(MyUtil.getUUID(),important,"平均为","average out(at)",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"通常；平均起来","on(an) average",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"高于平均价格卖出","average up",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"了解","have the awareness of",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"卸下","backing of",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"得到...的充分支持","have the full backing of",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"有大批的支持者","have a large backing",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"成为积压","become a backlog",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"获得(某物)作为储备物","acquire (sth) as a backlog",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"死账；坏账","bad debt",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"存心欺骗；不诚实","in bad faith",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"名声不佳","have a bad name",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"堕落；亏损","go to the bad",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"总的来说","on balance",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"悬而未决","in the balance",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"不稳","off balance",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"资产负债表","balance sheet",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"破产","go bankrupt",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"宣告破产","be declared bankrupt",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"完全缺乏，完全丧失","bankrupt of/in",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"破产，不能偿还债务；骗钱","play the bankrupt",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"自愿申请破产","voluntary bankruptcy",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"期望，信赖","bargain on",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"吃亏/赚钱的生意","a bad/good bargain",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"成交，达成一致","choose/seal bargain",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"在某事极力讨价还价；坚持苛刻的条件","drive a hard bargain over sth",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"大量订单","a batch of orders",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"批量生产","batch production",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"生产批次","production batch",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"压价；杀价","beat down",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"精疲力竭","be dead beat",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"大大超过某人；把某人打得一败涂地","beat sb hollow",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"公益","public benefit",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"共同利益","common benefit",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"长远利益","long-term benefit",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"哄抬；抬高出价数","bit up",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"付账；负责","foot the bill",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"在船上；在工作","on board",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"保税货物","bond goods",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"伪造账目","cook the books",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"贸易快速增长","a trade boom",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"提高价格","to boost prices",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"增压","pressure boost",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"除去根基；推翻","knock the bottom out of",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"跌到谷底","bottom out",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"根本上","at bottom",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"被解雇","get the bounce",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"解雇/开除/抛弃某人；与...断绝关系","give the bounce",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"回升；复苏","bounce back",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"自由讨论会","a brainstorming meeting",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"(事业)扩大规模","branch out",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"商标","brand mark",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"冒牌","imitation brand",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"突破","make a breakthrough",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"一封信","a brief letter",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"简单扼要","brief and to the point",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"假日指南","a holiday brochure",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"宣传手册","sales brochure",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"分期付款","budget plan",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"开始卸货","break bulk",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"散装；大量批发","in bulk",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"批发","sell in bulk",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"取消","call off",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"招标","to call for bit",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"收回，处理","call back",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"呼吁，拜访","call on",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"地方募集活动","community fund campaign",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"拉来订货","canvass for subscriptions",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"以某人的身份","in one's capacity",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"全力","at full capacity",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"作为...；以...为资格/身份/职位","as/in the capacity of",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"捞取...资本","make capital out of",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"货到付款","cash on arriver",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"将某物列入目录","list sth in a catalogue",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"注册会计师","certified accountant",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"连锁商店","chain store",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"通过正当的途径","through proper channel",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"管理，负责；具有对...控制或责任的","in charge of",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"附加费，服务费","cover charge",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"公司执照，公司注册证","corporate charter",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"特许证","charter of concession",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"登记(旅馆，机场，工作单位)","check in",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"结账，登记离去","check out",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"结账柜台","checkout counter",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"主要地，尤其","in chief",classify,time,status).save()
        Phrase(MyUtil.getUUID(),important,"最主要的是","chief of all",classify,time,status).save()

        Phrase(MyUtil.getUUID(),important,"开始流通","come into circulation",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"不再流通","get out of circulation",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"反索赔，反诉","counter claim",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"有对...的要求权","have a claim on",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"文职工作","clerical work",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"常年客户","regular client",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"亏本","catch a cold",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"商业广告时间","a commercial break",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"代理人，经纪人","commission agent",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"承担责任；(商业上的)约定","enter into commitment",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"短缺货物","a scarce commodity",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"赔钱货","distress commodity",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"与...联系","communication with",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"赔偿某人损失","compensate sb for lose",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"以...为报酬/赔偿","in compensation for",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"补偿某人的损失","make compensation for somebody's for loosed",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"为获得某物与某人竞争","compete with/against sb for sth",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"在...之间保持贸易竞争","keep trade competition between",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"可与...竞争的","competitive with",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"经济景况","economic condition",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"容许条件","admissible condition",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"固定结构","fixed configuration",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"电脑配置","computer configuration",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"和...冲突","come into conflict with",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"同...相冲突","in conflict with",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"商品竞争","commodity conflict",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"矿业集团","a mining conglomerate",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"建筑集团","a construction conglomerate",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"步步为营","consolidate at every step",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"合并账目","consolidate account",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"银行财团","banking consortium",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"一个忠实的伙伴","a constant companion",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"消费品","consumer goods",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"决策连续性","decision-making continuum",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"草拟合同","draw up a contract",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"缔结契约","negotiate contract",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"与...签订合同","make a contract with",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"建筑公司","general contractor",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"总承包人","prime contractor",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"共同出资","joint contribution",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"毛利","profit contribution",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"固定成本","fixed costs",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"日常管理成本","running costs",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"可变成本","variable costs",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"全部成本计算法","absorption costing",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"信用卡","credit card",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"赊购","credit sales",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"无担保债权人","unsecured creditor",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"经济危机","a economic crisis",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"金融危机","a financial crisis",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"信任危机","crisis of confidence",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"危机；紧要关头","critical moment",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"重大的决定","a critical decision",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"基准货币","basic currency",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"通用货币","current money",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"消费习惯","consumption custom",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"关税","custom duty/due",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"进口报关","customs entry",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"承包/投标截止日期","bid deadline",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"分配","deal out",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"经销","deal in",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"零售商","retail dealer",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"现金收入","cash debit",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"欠债","in debt",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"负债","to get into debt",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"借方和贷方","debtor and creditor",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"长期债务人","aged debtor",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"宣布作废，毁约；宣布退出","declare off",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"声明赞成某事","declare in favor of sth",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"拒绝请求","decline an offer",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"拒绝邀请","decline an invitation",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"直线下降","linear decrease",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"美中不足","have the defects of one's qualities",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"在没有...时；在没有...情况下","in defect of",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"无事故；无瑕疵","zero defects",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"不良率；不合格率","fraction defects",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"财政赤字","budget deficit",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"弥补亏损","cover the deficit",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"货到交付","delivery on line",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"需求管理","demand management",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"活期存款","current deposit",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"定期存款","time/dated deposit",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"服务站","server depot",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"使市场萧条","depress a market",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"请人代理做...","do sth by deputy",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"副主席","deputy chairman",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"饮食均衡","a balance diet",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"节食","to go on a diet",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"分工","differentiation of labor",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"把...寄给某人；直指","direct towards",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"企业名录","business directory",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"打85折","at 15% discount",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"打大折扣","heavy discount",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"解除某人的职务","dismiss sb for her/his post",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"被开除，被解雇","be dismissed form the server",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"被开除，被解雇","be dismissed form the server",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"散会","dismiss an assembly",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"开除","disciplinary dismissal",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"非法开除","wrongful dismissal",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"免费派遣","free dispatch",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"快速装卸","quick dispatch",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"正在展览的","on display",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"有...倾向；有意与...","dispose to",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"卖掉，解决","dispose of",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"使...多样化","diversify into",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"付一层股息","pay a 10% dividend",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"当头派；头","top dog",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"挺便宜的","dog-cheap",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"应得的报酬","due reward",classify,time,status)

        Phrase(MyUtil.getUUID(),important,"平均每小时收益","average hour eamings",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"总效率","aggregate efficiency",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"同意某人的观点","endorse one's opinions",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"预订房间","engage a room",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"加入谈话","engage in conversation",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"着手...；从事...","be engaged in/upon",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"正与...接洽；正忙于","be engaged with",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"应承，保证，担保，负责","engage for",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"开始(某种职业)","engage upon/on",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"对...享有权利；有做某事的资格；值得","be entitled to sth",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"实际产权","material equity",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"估计需求","estimated demand",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"夸张的广告宣传","exaggerate advertisement",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"越权","to exceed one's authority",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"规模突破","exceed in size",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"提供奖品","exhibit a price",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"超支","excessive expenditure",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"收支平衡","balance expenditure with income",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"支出账目","expense account",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"技术专长","technical expertise",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"器材/资源分配","facilities assignment",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"不动产","capital facility",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"设备的布局规划/计划","facilities layout",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"把...计算在内；包括","factor in",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"平均折扣率","average discount factor",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"故障后果","fail-out",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"安全系统","fail-safe system",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"没有销路的","fail-sale",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"绝不延迟","without fail",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"可行性研究","feasibility study",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"内部反馈","internal feedback",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"业务范围","business field",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"圆满回答一个问题","field a tough question",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"提交申请书","to file an application",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"填充，填补","fill in",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"履行工作义务","fill a post",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"满足需求","fill the requirement",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"市场金融","market finance",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"赤字财政","deficit finance",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"财力","financial ability",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"财务","financial affairs",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"经融恐慌，财政危机","financial crisis",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"金融巨头","a financial magnate",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"贷款筹措","loan financing",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"外部筹资","external financing",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"提供资本","capital financing",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"完成品","finished goods",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"成品","the finished product",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"固定的出价","a firm offer",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"政府的财政政策","the government's fiscal policy",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"决定","fix on",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"解决，商妥，安排","fix up",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"向...提供货物","fix up sb with goods",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"陷入困境","get oneself into a bad fix",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"陷入困境","fix a time to meet",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"旗舰店","flagship store",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"弹性预算","flexible-type-budget",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"发行公债","float a loan",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"资本倒流","reverse flow",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"资本流动","capital flow",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"波动的价格","fluctuate prices",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"细节落实","follow-up",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"然后发生的事；继任者","follow-on",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"如下","as follow",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"结果如下...","the result are as follow...",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"销售预测","sales forecast",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"行政机构，管理机构","administrative framework",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"授予特权","grant a franchise",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"撤销特权","withdraw a franchise",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"很多资料","a fund of information",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"公积金","a reserve fund",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"缺钱","out of fund",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"存款不足","no fund",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"作期货交易","deal in futures",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"收入和支出之间的差距","a gap between revenue and spending",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"预算困难","the budget gap",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"信用差距(指政府领导人的言行不一)","credibility gap",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"广告噱头","a advertising gimmick",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"有目的的","goal-directed",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"求职","go for a job",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"失败","go under",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"营业中的商行","a going concern",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"时价","the going price",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"事业发达","a going business",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"直接/间接必需品","goods of first/second order",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"交货","deliver the goods",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"正品","A-class goods",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"不合格品，次品","defective goods",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"与...搏斗；尽力解决","grapple with...",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"诉说自己的苦衷；发泄不满情绪","air one's grievance",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"怀恨某人；对某人心怀不满","nurse/have a grievance against sb",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"诉苦","pour out grievance",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"翻旧账","rip up old grievance",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"毛利","gross profits",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"国民生产总值(GDP)","gross domestic product",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"把...分组/归类为","group under",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"合并集团","consolidated group",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"由...长大；由...发展起来","grow from",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"终止同...的亲密关系","grow away from",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"国民经济各部门的平衡增长","balanced growth",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"替...担任保证人","stand guarantee for",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"以某物为担保物","offer sth as a guarantee",classify,time,status)
        Phrase(MyUtil.getUUID(),important,"购物指南","a shopper's guide",classify,time,status)
    }

    private fun addSentence(){
        var important = Constant.Important.primary
        var classify = Constant.SentenceClassify.life
        var status = Constant.Status.add
        var time = MyUtil.getTime()
        Sentence(MyUtil.getUUID(),important,"I quit!","我不干了！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Let go!","放手！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Me too.","我也是。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"My gosh!","天哪！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"No way!","不行！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Come on.","来吧(赶快)",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Hold on.","等一等。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I agree.","我同意。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Not bad.","还不错。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"See you.","再见。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Shut up!","闭嘴！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"So long.","再见。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Why not?","好呀！(为什么不呢？)",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Allow me.","让我来。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Be quiet!","安静点！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Cheer up!","振作起来！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Good job!","做得好！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Have fun!","玩得开心！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"How much?","多少钱？",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'm full.","我饱了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'm home.","我回来了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'm lost.","我迷路了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"My treat.","我请客。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"So do I.","我也一样。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"So do I.","我也一样。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"This way.","这边请。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"After you.","您先。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Bless you!","祝福你!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Follow me.","跟我来。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Forget it!","休想! (算了!)",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Good luck!","祝好运！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I decline!","我拒绝！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I promise.","我保证。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Of course!","当然了！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Slow down!","慢点！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Take care!","保重！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"They hurt.","(伤口)疼。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Try again.","再试试。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Watch out!","当心。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What's up?","有什么事吗?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Be careful!","注意!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Bottoms up!","干杯(见底)",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Don't move!","不许动！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Guess what?","猜猜看？",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I doubt it.","我怀疑。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I think so.","我也这么想",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'm single.","我是单身贵族。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Keep it up!","坚持下去!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Let me see.","让我想想",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Never mind.","不要紧。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"No problem!","没问题！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"That's all!","就这样！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Time is up.","时间快到了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What's new?","有什么新鲜事吗?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Count me on","算上我。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Don't worry.","别担心。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Feel better?","好点了吗?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I love you!","我爱你！",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'm his fan.","我是他的影迷。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Is it yours?","这是你的吗?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"That's neat.","这很好。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Are you sure?","你肯定吗?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Do l have to","非做不可吗?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He is at my age.","他和我同岁。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Here you are.","给你。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"No one knows.","没有人知道。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Take it easy.","别紧张。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What a pity!","太遗憾了!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Anything else?","还要别的吗?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"To be careful!","一定要小心!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Do me a favor?","帮个忙，好吗?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Help yourself.","别客气。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'm on a diet.","我在节食。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Keep in Touch.","保持联络。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Time is money.","时间就是金钱。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Who s calling?","是哪一位?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"You did right.","你做得对。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"You set me up!","你出卖我!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Can I help you?","我能帮你吗?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Enjoy yourself!","祝你玩得开心!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Excuse me, Sir.","先生，对不起。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Give me a hand!","帮帮我!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"How s it going?","怎么样?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I have no idea.","我没有头绪。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I just made it!","我做到了!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'll see to it","我会留意的。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'm in a hurry!","我在赶时间!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It s her field.","这是她的本行。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It s up to you.","由你决定。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Just wonderful!","简直太棒了!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What about you?","你呢?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"You owe me one.","你欠我一个人情。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"You re welcome. ","不客气。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Any day will do.","哪一天都行。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Are you kidding?","你在开玩笑吧!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Congratulations!","祝贺你!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I can't help it.","我情不自禁。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I dont't mean it.","我不是故意的。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'll fix you up.","我会帮你打点的",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It sounds great!","听起来很不错。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It s a fine day.","今天是个好天。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"So far, So good.","目前还不错。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What time is it?","几点了?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"You can make it!","你能做到!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Control yourself!","克制一下!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He came by train.","他乘火车来。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He is ill in bed.","他卧病在床。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He lacks courage.","他缺乏勇气。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"How s everything?","一切还好吧?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I have no choice.","我别无选择。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I like ice-cream.","我喜欢吃冰淇淋。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I love this game.","我钟爱这项运动。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'll try my best.","我尽力而为。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'm on your MyUtil.getUUID()e.","我全力支持你。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Long time no see!","好久不见!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"No pain, no gain.","不劳无获。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Well, it depends","噢，这得看情况。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"We re all for it.","我们全都同意。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What a good deal!","真便宜!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What should I do?","我该怎么办？",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"You asked for it!","你自讨苦吃!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"You have my word.","我保证。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Believe it or not!","信不信由你!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Don't count on me.","别指望我。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Don't fall for it!","别上当!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Don't let me down. ","别让我失望。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Easy come, easy go.","来得容易，去得快。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I beg your pardon.","请你原谅。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I beg your pardon?","请您再说一遍(我没有听清",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'll be back soon.","我马上回来。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'll check it out.","我去查查看。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It’s a long story.","说来话长。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It’s Sunday today.","今天是星期天。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Just wait and see!","等着瞧!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Make up your mind.","做个决定吧。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"That's all I need.","我就要这些。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"The view is great.","景色多么漂亮!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"The wall has ears.","隔墙有耳。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"There comes a bus.","汽车来了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What day is today?","今天星期几?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What do you think?","你怎么认为？",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Who told you that?","谁告诉你的?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Who s kicking off?","现在是谁在开球?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Yes, I suppose so.","是的，我也这么认为。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"You can't miss it.","你一定能找到的。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Any messages for me?","有我的留言吗?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Don't be so modest．","别谦虚了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Don't give me that!","少来这套!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He is a smart boy．","他是个小机灵鬼。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He is just a child．","他只是个孩子。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I can't follow you．","我不懂你说的。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I felt sort of ill.","我感觉有点不适。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I have a good idea!","我有一个好主意。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It is growing cool．","天气渐渐凉爽起来。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It seems all right．","看来这没问题。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It s going too far．","太离谱了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"May I use your pen? ","我可以用你的笔吗?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"She had a bad cold．","她患了重感冒。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"That's a good idea．","这个主意真不错。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"The answer is zero．","白忙了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What does she like? ","她喜欢什么?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"As soon as possible!","越快越好!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He can hardly speak．","他几乎说不出话来。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He always talks big．","他总是吹牛。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He won an election．","他在选举中获胜。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I am a football fan．","我是个足球迷。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"If only I could fly．","要是我能飞就好了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'll be right there．","我马上就到。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'll see you at six．","我六点钟见你。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"IS it true or false?","这是对的还是错的?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Just read it for me．","就读给我听好了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Knowledge is power． ","知识就是力量。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Move out of my way! ","让开!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Time is running out．","没时间了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"We are good friends．","我们是好朋友。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What's your trouble?","你哪儿不舒服?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"You did fairly well!","你干得相当不错。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Clothes make the man．","人要衣装。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Did you miss the bus?","你错过公共汽车了?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Don't lose your head。","不要惊慌失措。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He can't take a joke．","他开不得玩笑。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He owes my uncle $100","他欠我叔叔100美元。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"How are things going?","事情进展得怎样?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"How are you recently?","最近怎么样?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I know all about it. ","我知道有关它的一切。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It really takes time.","这样太耽误时间了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It s against the law.","这是违法的。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Love me, love my dog.","(谚语)爱屋及乌。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"My mouth is watering．","我要流口水了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Speak louder，please．","说话请大声点儿。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"This boy has no job．","这个男孩没有工作。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"This house is my own．","这所房子是我自己的。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What happened to you?","你怎么了?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"You are just in time.","你来得正是时候。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"You need to workout．","你需要去运动锻炼一下。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Your hand feels cold．","你的手摸起来很冷。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Don't be so childish.","别这么孩子气。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Don't trust to chance!","不要碰运气。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Fasten your seat belt．","系好你的安全带。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He has a large income.","他有很高的收入。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He looks very healthy．","他看来很健康。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He paused for a reply．","他停下来等着?回答。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He repaired his house．","他修理了他的房子。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He suggested a picnic.","他建议搞一次野餐。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Here's a gift for you．","这里有个礼物送给你。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"How much does it cost?","多少钱?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I caught the last bus.","我赶上了最后一班车。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I could hardly speak．","我简直说不出话来。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'll have to try that．","我得试试这么做。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'm very proud of you．","我为你感到非常骄傲。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It doesn't make sense.","这没有意义(不合常理)。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Make yourself at home．","请不要拘礼。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"My car needs washing． ","我的车需要洗一洗。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"None of your business!","与你无关!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Not a sound was heard.","一点声音也没有。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"That's always the case.","习以为常了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"The road divides here.","这条路在这里分岔。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Those are watermelons．","那些是西瓜。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What a nice day it is!","今天天气真好!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What's wrong with you?","你哪里不对劲?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"You are a chicken．","你是个胆小鬼。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"A lovely day，isn t it?","好天气，是吗?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He is collecting money．","他在筹集资金。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He was born in New York.","他出生在纽约。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He was not a bit tired．","他一点也不累。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I will be more careful．","我会小心一些的。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I will never forget it．","我会记着的。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It is Just what I need．","这正是我所需要的。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It rather surprised me．","那事使我颇感惊讶。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Just around the comer．","就在附近。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Just for entertainment．","只是为了消遣一下。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Let bygones be bygones．","过去的，就让它过去吧。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Mother doesn't make up．","妈妈不化妆。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Oh，you are kidding me．","哦，你别拿我开玩笑了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"She has been to school.","她上学去了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Skating is interesting.","滑冰很有趣。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Supper is ready at six.","晚餐六点钟就好了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"That's a terrific idea!","真是好主意!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"What horrible weather! ","这鬼天气!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Which would you prefer?","你要选哪个?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Does she like ice-cream?","她喜欢吃冰淇淋吗?",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"First come first served.","先到先得。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Great minds think alike.","英雄所见略同。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He has a sense of humor.","他有幽默感。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He is acting an old man.","他正扮演一个老人。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He is looking for a job.","他正在找工作。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He doesn't care about me.","他并不在乎我。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I develop films myself.","我自己冲洗照片。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I felt no regret for it.","对这件事我不觉得后悔。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I get up at six o clock.","我六点起床。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I meet the boss himself.","我见到了老板本人。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I owe you for my dinner.","我欠你晚餐的钱。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I really enjoyed myself.","我玩得很开心。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'm fed up with my work!","我对工作烦死了!",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"It s no use complaining.","发牢骚没什么用。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"She s under the weather.","她心情不好。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"The child sobbed sadly.","小孩伤心地抽泣着。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"The rumor had no basis.","那谣言没有根据。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"They praised him highly.","他们大大地表扬了他。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Winter is a cold season.","冬天是一个，寒冷的季节。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"You can call me any time.","你可以随时打电话给我。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"15 divided by 3 equals 5.","15除以3等于5。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"All for one, one for all.","我为人人，人人为我。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"East or west, home is the best.","金窝，银窝，不如自己的草窝。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He grasped both my hands.","他紧握住我的双手。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"He is physically mature.","他身体己发育成熟。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I am so sorry about this.","对此我非常抱歉(遗憾)。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I can't afford a new car.","我买不起一部新车。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I do want to see him now.","我现在确实很想去见他。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I have the right to know.","我有权知道。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I heard someone laughing.","我听见有人在笑。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I suppose you often dance.","我想你常常跳舞吧。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I walked across the park.","我穿过了公园。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'll just play it by ear.","我到时随机应变。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'm not sure I can do it.","恐怕这事我干不了。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"I'm not used to drinking.","我不习惯喝酒。",classify,time,status).save()
        Sentence(MyUtil.getUUID(),important,"Is the cut still painful?","伤口还在痛吗?",classify,time,status).save()
    }

    override fun initViews(view: View, bundle: Bundle?) {
        mBinding.addWords.setOnClickListener {
            addWords()
        }

        mBinding.addPhrase.setOnClickListener {
            addPhrase()
        }

        mBinding.addSentence.setOnClickListener {
            addSentence()
        }
    }
}